package com.course.exceptions;

import java.io.IOException;

public class TestFinally1 {

	public static void main(String[] args) {
//		try{
//			openFile();
//			
//			useFile();
//			useFileSomeMore();
//			useFileSomeMore();
//			useFileSomeMore();
//		}
//		catch (IOException e)
//		{
//			dealWithError();
//			return;
//		}
//		finally {
//			// This will always be called.
//			closeFile();
//		}
//		
		
		
	}

}

